"""empty message

Revision ID: f3ebfcc00680
Revises: 
Create Date: 2020-02-18 14:28:29.382645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f3ebfcc00680'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'discount',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('orders', 'gift',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('orders', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('orders', 'total',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('products', 'version',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('returns', sa.Column('partial', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('returns', 'partial')
    op.alter_column('products', 'version',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'total',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('orders', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('orders', 'gift',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('orders', 'discount',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###
